version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  flask-app:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env
